### ISSUE TITLE
Rateries génériques (migration, affichage...)

### ISSUE THREAD

**Issue by VigiePirate** [VigiePirate/CakeLORD#158]
Migration :
- Harmoniser les étoiles, espaces et majuscule actuellement disparates, je propose ceci : 
```
    - *Éleveur indépendant*
    - *Éleveur étranger*
    - *Lignée de laboratoire*
    - *Sauvetage*
    - *Rat sauvage*
```
- ou la même chose avec espace : 
```
    - * Éleveur indépendant *
    - * Éleveur étranger *
    - * Lignée de laboratoire *
    - * Sauvetage *
    - * Rat sauvage *
```
- Ajouter les É à Éleveur indépendant et Éleveur étranger
- L'origine SOS ne se voit attribuer aucun rat. Ne faudrait-il pas lui donner tous les rats précédemment sous INC + origine "Sauvetage" (le nouveau * Animalerie * ne recevant que les anciens INC + origine "Animalerie" ?)
- Est-ce que les rateries génériques ne devraient pas plutôt appartenir au compte LORD ?

Code : 
- Ne pas afficher la lune pour inactivité
- Ne pas désactiver automatiquement lors de la routine de connexion staff
- Peut-être ajouter et afficher un commentaire explicatif ?

**Comment by PetitangePA** [comment]
Les rateries génériques ont été corrigées post migration
