### ISSUE TITLE
Fiches qui reviennent au SAV après 15 jours - Multiplication de la même notification

### ISSUE THREAD

**Issue by PetitangePA** [VigiePirate/CakeLORD#212]
Ce matin, 112 fiches sont revenues au SAV.
J'en prends une au hasard : https://lord.srfa.info/rats/view/58222

J'ai 79 notifications identiques "La fiche est revenue au SAV faute de correction dans les temps."

![image](https://github.com/VigiePirate/CakeLORD/assets/42876414/ae87f738-572b-4925-ae7e-b9a383dfacbe)

**Comment by VigiePirate** [comment]
Quickfix appliqué dans #213. La génération de messages automatiques sera peut-être à améliorer globalement, après debrief fonctionnel (trop de messages ?)
